- name: Assert usage of systemd or upstart as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: victoria_metrics_systemd_version_result

- name: Set systemd version fact
  set_fact:
    victoria_metrics_systemd_version: "{{ victoria_metrics_systemd_version_result.stdout_lines[0].split(' ')[-1] }}"
